{{- range .Values.applications }}
{{- $name := .name }}
{{- $namespace := .namespace | default "default" }}
{{- $project := .project | default $.Values.defaults.project }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.defaults.env | default "env" }}-{{ $.Values.defaults.destination.namespace | default "default" }}-{{ $name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: {{ $project }}
  destination:
    namespace: {{ $.Values.defaults.env | default "env" }}-{{ $.Values.defaults.destination.namespace | default "default" }}
    server: {{ $.Values.defaults.destination.server | default "https://kubernetes.default.svc" }}
  {{- if and .source (not .sources) }}
  source:
{{ toYaml .source | nindent 4 }}
  {{- else if and .sources (not .source) }}
  sources:
{{ toYaml .sources | nindent 4 }}
  {{- else }}
  {{- fail (printf "Application '%s' must define either 'source' or 'sources', but not both." $name) }}
  {{- end }}



  {{- if .syncPolicy }}
  syncPolicy:
{{ toYaml .syncPolicy | nindent 4 }}
  {{- else if $.Values.defaults.syncPolicy }}
  syncPolicy:
{{ toYaml $.Values.defaults.syncPolicy | nindent 4 }}
  {{- end }}
{{- end }}